sudo: false
language: python
python: 3.7

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - cd app/ && pipenv install --dev

script:
  - pipenv run coverage_travis

after_success:
  - pipenv run coveralls
